services:
  the_room.telegram_bot.route.loader:
    class: TheRoom\TelegramBotBundle\Routing\RouteLoader
    calls:
      - [setRoutePath, ["%the_room_telegram_bot.routePath%"]]
    tags:
      - { name: routing.loader }
